name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Test Windows Scripts
      run: |
        # Test batch script
        cmd /c "scripts\windows\pm-agent-config.bat --help"
        # Test PowerShell syntax
        powershell -Command "Get-Content scripts\windows\pm-agent-config.ps1 | Out-Null"

  test-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Test Linux Scripts
      run: |
        # Test shell script syntax and help
        bash -n scripts/linux/pm-agent-config.sh
        bash scripts/linux/pm-agent-config.sh --help

  quality-checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      with:
        scandir: './scripts'
    - name: Validate Documentation
      run: |
        # Check required files exist
        for file in README.md CHANGELOG.md CONTRIBUTING.md LICENSE SECURITY.md DEPLOYMENT.md docs/windows-guide.md docs/linux-guide.md; do
          test -f "$file" || { echo "Missing: $file"; exit 1; }
        done
        echo "All documentation files present"
